image: clever/drone-go:1.7
notify:
  email:
    recipients:
    - drone@clever.com
  slack:
    on_failure: true
    on_started: false
    on_success: false
    webhook_url: $$slack_webhook
publish:
  github:
    artifacts:
    - sphinx-amd64.deb
    repo: sphinx
    script:
    - make deb
    - cp deb/sphinx.deb sphinx-amd64.deb
    tag: v$(cat deb/sphinx/DEBIAN/control | grep Version | cut -d " " -f 2)
    token: $$github_token
    user: Clever
    when:
      branch: master
  docker:
    docker_host: $$docker_server
    email: $$docker_email
    image_name: clever/sphinx
    password: $$docker_password
    registry_login: true
    tags:
    - $(git rev-parse --short HEAD)
    username: $$docker_username
    when:
      branch: master
  report_card: {}
script:
- make test
- make build
