#!/bin/sh
set -e

case "$1" in
  abort-upgrade|abort-remove|abort-deconfigure|configure)
    ;;

  *)
    echo "postinst called with unknown argument \`$1'" >&2
    exit 1
    ;;
esac

echo "Bringing up the Sphinx..."
if [ -f /etc/init/sphinx.conf ]; then
    if pidof /usr/local/bin/sphinxd >/dev/null; then
        service sphinx stop || exit $?
    fi
    service sphinx start && echo "Started. Sphinx now on guard."
fi

#DEBHELPER#

exit 0
