#!/bin/sh
set -e

case "$1" in
  abort-upgrade|abort-remove|abort-deconfigure|configure)
    ;;

  *)
    echo "postinst called with unknown argument \`$1'" >&2
    exit 1
    ;;
esac

echo "Bringing up the Sphinx..."
if [ -f /etc/systemd/system/sphinx.service ]; then
    if pidof /usr/local/bin/sphinxd >/dev/null; then
        systemctl stop sphinx.service || exit $?
    fi
    systemctl start sphinx.service && echo "Started. Sphinx now on guard."
fi

#DEBHELPER#

exit 0
